Update README.md
DIT112-V20/group-07 pull request #115
Opened 2020-05-29 10:02 UTC by oscarhjern

2020-05-29 11:02 UTC, WhiteMaken requested changes

2020-05-29 11:02 UTC, WhiteMaken commented on README.md
> +Sensors that need calibiration:
Fix typo in "calibration".

2020-05-29 11:02 UTC, WhiteMaken commented on README.md
> +Methods that need calibiration:
Fix typo in "calibration".

2020-05-29 11:11 UTC, WhiteMaken commented on README.md
> +- Attach one MICRO LIDAR SENSOR directly to the left side of the car
maybe micro lidar sensor should not be uppercase? looks a bit out of place.

2020-05-29 11:12 UTC, WhiteMaken commented on README.md
> +- MICRO LIDAR SENSOR
maybe micro lidar sensor should not be uppercase? looks a bit out of place.

2020-05-30 14:59 UTC, majawennroth commented on README.md
> +- [Maja Wennroth](https://github.com/majawennroth), Car Wizard
I would prefer car responsibel

2020-05-30 15:05 UTC, majawennroth approved these changes

2020-05-30 15:06 UTC, WhiteMaken approved these changes

2020-05-30 15:06 UTC, WhiteMaken commented on README.md
> +- [Maximilien Uddgren](https://github.com/WhiteMaken), App Guy
Everyone has cool titles but Mike and me have "app guys", so sad :(

2020-05-30 15:08 UTC, majawennroth approved these changes

2020-05-30 15:17 UTC, merged